Vagrant.configure("2") do |config|
    config.vm.box="dreamcloud/centos7"
    config.ssh.insert_key = false
    config.vm.box_check_update = false

    config.vm.define "ctopenstack" do |ct7|
        ct7.vm.hostname = "ctopenstack"
        ct7.vm.network :private_network, ip: "10.120.0.21"

        ct7.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
            vb.name="ctopenstack"
            vb.memory=4096
            vb.cpus=2
        end
    end
end
