# Vagrantfile
# build up a centos k8s cluster
# By Robert Wang @github.com/robertluwang
# Jan 3rd, 2018

$masterScript = <<SCRIPT

# update centos7k8s-master /etc/hosts
sudo sed -i  '/centos7k8s/d' /etc/hosts
sudo sed -i "1i10.120.0.15        centos7k8s-master" /etc/hosts
sudo sed -i "2i10.120.0.16        centos7k8s-node" /etc/hosts

# turn off swap
sudo swapoff -a
sudo sed -i '/swap/d' /etc/fstab

# trun off firewall
sudo systemctl disable firewalld
sudo systemctl stop firewalld

# create k8s cluster with calico network
sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=10.120.0.15 |tee /tmp/kubeadm.log

cat /tmp/kubeadm.log  | grep "kubeadm join" > $HOME/jointoken

#rm $HOME/kubeadm.log

# allow normal user to run kubectl 
if [ -d $HOME/.kube ]; then
  rm -r $HOME/.kube
fi 
mkdir -p $HOME/.kube 
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config                                         
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# install calico network addon
kubectl apply -f  https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml

# allow run on master
kubectl taint nodes --all node-role.kubernetes.io/master-

SCRIPT

$nodeScript = <<SCRIPT

# update centos7k8s-node /etc/hosts
sudo sed -i  '/centos7k8s/d' /etc/hosts
sudo sed -i "1i10.120.0.15        centos7k8s-master" /etc/hosts
sudo sed -i "2i10.120.0.16        centos7k8s-node" /etc/hosts

# turn off swap
sudo swapoff -a
sudo sed -i '/swap/d' /etc/fstab

# add private key 
curl -Lo $HOME/.ssh/vagrant https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant
chmod 0600 $HOME/.ssh/vagrant

# join cluster
scp -q -o "StrictHostKeyChecking no" -i $HOME/.ssh/vagrant  centos7k8s-master:$HOME/jointoken  $HOME/jointoken  
sudo sh $HOME/jointoken

SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box="dreamcloud/centos7k8s"
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    
    config.vm.define "centos7k8s-master" do |master|
        master.vm.hostname = "centos7k8s-master"
        master.vm.network :private_network, ip: "10.120.0.15"
        master.vm.network "forwarded_port", guest: 8443, host: 8443, protocol: "tcp"
        master.vm.network "forwarded_port", guest: 30000, host: 30000, protocol: "tcp"
      
        master.vm.provision "shell", inline: "date; echo master provision starting", privileged: false
        master.vm.provision "shell", inline: $masterScript, privileged: false
        master.vm.provision "shell", inline: "date; echo master provision finished", privileged: false
  
        master.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.name="centos7k8s-master"
            vb.memory=1024
        end
    end
    
    config.vm.define "centos7k8s-node" do |node|
        node.vm.hostname = "centos7k8s-node"
        node.vm.network :private_network, ip: "10.120.0.16"
       
        node.vm.provision "shell", inline: "date; echo node provision starting", privileged: false
        node.vm.provision "shell", inline: $nodeScript, privileged: false
        node.vm.provision "shell", inline: "date; echo node provision finished", privileged: false
                
        node.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.name="centos7k8s-node"
            vb.memory=1024
        end
    end
end


