# Vagrantfile
# build up a centos k8s box from base box
# By Robert Wang @github.com/robertluwang
# Jan 3rd, 2018

Vagrant.configure("2") do |config|
    config.vm.box="centos/7"
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    
    config.vm.define "centos7k8s" do |ck8s|
        ck8s.vm.hostname = "centos7k8s"
        
        
        ck8s.vm.provision "shell", inline: "date; echo centos7k8s provision starting", privileged: false
        ck8s.vm.provision "shell", path: "../scripts/centos-basebox.sh"
        ck8s.vm.provision "shell", path: "../scripts/centos-k8sbox.sh"
        ck8s.vm.provision "shell", path: "../scripts/centos-vbguest.sh"
        ck8s.vm.provision "shell", path: "../scripts/centos-publickey.sh"
        ck8s.vm.provision "shell", path: "../scripts/centos-cleanup.sh"
        ck8s.vm.provision "shell", inline: "date; echo centos7k8s provision finished", privileged: false
        
        ck8s.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
            vb.name="centos7k8s"
            vb.memory=1024
        end
    end
end
